### PR TITLE
Syntax improvements

### PR DESCRIPTION
**Pull request by Inityx**

### CODE REVIEW

**Review by Codysseus — CHANGES_REQUESTED** [review]
Please move simplification of types into a separate PR. This PR should be specifically for syntax improvements.

**Comment by Inityx** [comment]
I would but some of them are interdependent and Aaron won't even approve one PR, let alone two :^)

**Comment by Codysseus** [comment]
Surely you could remove the `register.hpp` improvement?

**Comment by aaronschraner** [comment]
Hey guys, this code actually didn't end up being used on the project. The code that's here can only do a very small fraction of what we needed it to. In the interest of meeting the project deadline and making it easier for our stakeholder to build on, we rewrote it in Arduino.

**Pull request closed without merging**
